### ISSUE TITLE
Blur not working

### ISSUE THREAD

**Issue by Coldlolololir** [dannylol19/syn-round#1]
Blur isn't working when set to true
![image](https://user-images.githubusercontent.com/78960389/174330182-f4fe7209-6f7f-42da-bed8-7fc24d7f4fc4.png)

**Comment by dannylol19** [comment]
Yup, forgot I left the theme non transparent. Download the latest release and I added a folder that has the transparent theme.
You should also try setting your own transparency in theme-wpf.json:
![](https://cdn.discordapp.com/attachments/876284350499540995/987566816475902002/unknown.png)
Sorry for not clarifying any of this in the README.md file. It has now been updated aswell.

**Comment by dannylol19** [comment]
closing, assuming issue was fixed
